import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import McpPageTracker from "./components/McpPageTracker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script id="data-layer-init" strategy="beforeInteractive">
          {`window.dataLayer = window.dataLayer || [];`}
        </Script>
        <Script
          src="https://cdn.evgnet.com/beacon/a556rq555550mxe43n3n3n091568480/demos/scripts/evergage.min.js"
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <McpPageTracker />
        <div id="product-recommendation" className="global-product-recommendation" aria-hidden="true" />
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
